echo [*]This Script will install neccessary Dependencies......
echo [*]Prompt Chat*************
apt install python3-pip
pip3 install termcolor
echo [*]All Dependencies were Successfully installed....
